##### MQTT #####
mqtt:
  broker: "localhost" # MQTT broker hostname/IP
  port: 1883 # MQTT broker port
  username: null # Optional
  password: null # Optional
  client_id: "webhook-bridge" # Must be unique
  keepalive: 60 # Keepalive interval in seconds

##### ROUTES #####
routes:
  # Example 1: Set temperature with query parameters
  - path: "/set_temperature"
    method: "POST"
    mqtt_topic: "command/set_temperature/{room}"
    parameters:
      - name: "room"
        type: "string"
        required: true
        location: "query"
      - name: "target"
        type: "float"
        required: true
        location: "query"
    payload_template: |
      {
        "room": "{{room}}",
        "target_temperature": {{target}}
      }
    qos: 1
    retain: false

  # Example 2: Control light with path and body parameters
  - path: "/set_light/{room}"
    method: "POST"
    mqtt_topic: "command/light"
    parameters:
      - name: "room"
        type: "string"
        required: true
        location: "path"
      - name: "state"
        type: "string"
        required: true
        location: "body"
      - name: "brightness"
        type: "integer"
        required: false
        location: "body"
        default: 100
    payload_template: |
      {
        "room": "{{room}}",
        "state": "{{state}}",
        "brightness": {{brightness}}
      }
    qos: 1
    retain: false

  # Example 3: Simple device command
  - path: "/device/{device_id}/command"
    method: "POST"
    mqtt_topic: "devices/{device_id}/cmd"
    parameters:
      - name: "device_id"
        type: "string"
        required: true
        location: "path"
      - name: "action"
        type: "string"
        required: true
        location: "query"
      - name: "value"
        type: "string"
        required: false
        location: "query"
        default: ""
    payload_template: |
      {
        "action": "{{action}}",
        "value": "{{value}}"
      }
    qos: 0
    retain: false

  # Example 4: Sensor data submission
  - path: "/sensor/data"
    method: "POST"
    mqtt_topic: "sensors/data"
    parameters:
      - name: "sensor_id"
        type: "string"
        required: true
        location: "body"
      - name: "temperature"
        type: "float"
        required: false
        location: "body"
      - name: "humidity"
        type: "float"
        required: false
        location: "body"
      - name: "pressure"
        type: "float"
        required: false
        location: "body"
    payload_template: |
      {
        "sensor_id": "{{sensor_id}}",
        "temperature": {{temperature if temperature else 'null'}},
        "humidity": {{humidity if humidity else 'null'}},
        "pressure": {{pressure if pressure else 'null'}}
      }
    qos: 1
    retain: false
